### ISSUE TITLE
为啥我的报空指针错误

### ISSUE THREAD

**Issue by cywang4** [dotbalo/ratel-doc#2]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x139b429]

goroutine 1 [running]:
ratel/initConf.LoadClusterList(0x7ffc7fcdf85a, 0x11, 0x1921ea0, 0xc0001160e0, 0x0)
	D:/code/GoCode/src/ratel/initConf/initConf.go:126 +0x939
ratel/initConf.initClusterConf(0x7ffc7fcdf85a, 0x11, 0x0, 0x0, 0x0)
	D:/code/GoCode/src/ratel/initConf/initConf.go:38 +0x8c
ratel/initConf.Init(0x7ffc7fcdf85a, 0x11)
	D:/code/GoCode/src/ratel/initConf/init.go:56 +0x71a
main.main()
	D:/code/GoCode/src/ratel/main.go:27 +0xdd

**Comment by dotbalo** [comment]
您好，应该是没有加载到配置文件
