### ISSUE TITLE
ratel容器启动后报这个错误，不知道怎么办。

### ISSUE THREAD

**Issue by sainoy-404** [dotbalo/ratel-doc#6]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45b5de]
goroutine 1 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0x0, 0x17158c0, 0xc00006bcc0, 0x2)
	D:/code/GoCode/src/k8s.io/client-go/kubernetes/clientset.go:355 +0x4e
ratel/initConf.LoadClusterList(0x7ffcbf436249, 0x11, 0x0, 0x0, 0x0)
	D:/code/GoCode/src/ratel/initConf/initConf.go:95 +0x793
ratel/initConf.initClusterConf(0x7ffcbf436249, 0x11, 0x0, 0x0, 0x0)
	D:/code/GoCode/src/ratel/initConf/initConf.go:38 +0xa6
ratel/initConf.Init(0x7ffcbf436249, 0x11)
	D:/code/GoCode/src/ratel/initConf/init.go:49 +0x473
main.main()
	D:/code/GoCode/src/ratel/main.go:27 +0xdd

**Comment by dotbalo** [comment]
@sainoy-404 您好，可以把配置文件贴一下，一般这个问题都是配置文件不对导致的。
