### ISSUE TITLE
ratel  可以正常open web  但是无法链接 k8s 数据

### ISSUE THREAD

**Issue by qinxiaohai** [dotbalo/ratel-doc#7]
2021/04/20 12:56:28.885 [I] [value.go:476]  距离上次加载主页数据已经超过:0秒,重新加载数据
2021/04/20 12:56:28.885 [I] [clusterinfo.go:34]  获取到当前API接口: Nodes
2021/04/20 12:56:28.885 [I] [clusterinfo.go:34]  获取到当前API接口: Daemonsets
2021/04/20 12:56:28.885 [I] [clusterinfo.go:34]  获取到当前API接口: Deployments
2021/04/20 12:56:28.885 [I] [clusterinfo.go:34]  获取到当前API接口: Statefulsets
2021/04/20 12:56:28.885 [I] [clusterinfo.go:34]  获取到当前API接口: Pods
2021/04/20 12:56:28.885 [I] [clusterinfo.go:34]  获取到当前API接口: Namespaces
2021/04/20 12:56:28.885 [I] [clusterinfo.go:34]  获取到当前API接口: Services
2021/04/20 12:56:28.885 [I] [clusterinfo.go:34]  获取到当前API接口: Ingresses
2021/04/20 12:56:28.885 [I] [clusterinfo.go:34]  获取到当前API接口: Secrets
2021/04/20 12:56:28.885 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Secrets
2021/04/20 12:56:28.885 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Secrets数量
2021/04/20 12:56:28.886 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Nodes
2021/04/20 12:56:28.886 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Nodes数量
2021/04/20 12:56:28.886 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Daemonsets
2021/04/20 12:56:28.886 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Daemonsets数量
2021/04/20 12:56:28.886 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Deployments
2021/04/20 12:56:28.886 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Deployments数量
2021/04/20 12:56:28.887 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Statefulsets
2021/04/20 12:56:28.887 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Statefulsets数量
2021/04/20 12:56:28.887 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Pods
2021/04/20 12:56:28.887 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Pods数量
2021/04/20 12:56:28.887 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Namespaces
2021/04/20 12:56:28.887 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Namespaces数量
2021/04/20 12:56:28.888 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Services
2021/04/20 12:56:28.888 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Services数量
2021/04/20 12:56:28.888 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Ingresses
2021/04/20 12:56:28.888 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Ingresses数量
2021/04/20 12:56:32.675 [I] [value.go:476]  距离上次加载主页数据已经超过:0秒,重新加载数据
2021/04/20 12:56:32.675 [I] [clusterinfo.go:34]  获取到当前API接口: Nodes
2021/04/20 12:56:32.675 [I] [clusterinfo.go:34]  获取到当前API接口: Daemonsets
2021/04/20 12:56:32.675 [I] [clusterinfo.go:34]  获取到当前API接口: Deployments
2021/04/20 12:56:32.675 [I] [clusterinfo.go:34]  获取到当前API接口: Statefulsets
2021/04/20 12:56:32.675 [I] [clusterinfo.go:34]  获取到当前API接口: Pods
2021/04/20 12:56:32.675 [I] [clusterinfo.go:34]  获取到当前API接口: Namespaces
2021/04/20 12:56:32.675 [I] [clusterinfo.go:34]  获取到当前API接口: Services
2021/04/20 12:56:32.675 [I] [clusterinfo.go:34]  获取到当前API接口: Ingresses
2021/04/20 12:56:32.675 [I] [clusterinfo.go:34]  获取到当前API接口: Secrets
2021/04/20 12:56:32.675 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Secrets
2021/04/20 12:56:32.675 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Secrets数量
2021/04/20 12:56:32.677 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Nodes
2021/04/20 12:56:32.677 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Nodes数量
2021/04/20 12:56:32.678 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Daemonsets
2021/04/20 12:56:32.678 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Daemonsets数量
2021/04/20 12:56:32.679 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Deployments
2021/04/20 12:56:32.679 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Deployments数量
2021/04/20 12:56:32.680 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Statefulsets
2021/04/20 12:56:32.680 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Statefulsets数量
2021/04/20 12:56:32.680 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Pods
2021/04/20 12:56:32.680 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Pods数量
2021/04/20 12:56:32.681 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Namespaces
2021/04/20 12:56:32.681 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Namespaces数量
2021/04/20 12:56:32.682 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Services
2021/04/20 12:56:32.682 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Services数量
2021/04/20 12:56:32.683 [I] [getClusterInfoHandler.go:45]  当前查询的集群为:test1, 资源的类型为:Ingresses
2021/04/20 12:56:32.683 [I] [getClusterInfoHandler.go:45]  查看集群serverName:test1的Ingresses数量
2021/04/20 12:56:58.887 [E] [getClusterInfoHandler.go:26]  获取StatefulSet节点数量失败, err: Get "https://192.168.0.126:6443/apis/apps/v1/statefulsets": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:56:58.888 [I] [getClusterInfoHandler.go:45]  查询到Statefulsets的数量为:0
2021/04/20 12:56:58.888 [E] [getClusterInfoHandler.go:20]  获取Node节点数量失败, err: Get "https://192.168.0.126:6443/api/v1/nodes": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:56:58.888 [I] [getClusterInfoHandler.go:45]  查询到Nodes的数量为:0
2021/04/20 12:56:58.888 [E] [getClusterInfoHandler.go:22]  获取DaemonSet节点数量失败, err: Get "https://192.168.0.126:6443/apis/apps/v1/daemonsets": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:56:58.888 [I] [getClusterInfoHandler.go:45]  查询到Daemonsets的数量为:0
2021/04/20 12:56:58.888 [E] [getClusterInfoHandler.go:24]  获取Deployment节点数量失败, err: Get "https://192.168.0.126:6443/apis/apps/v1/deployments": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:56:58.888 [I] [getClusterInfoHandler.go:45]  查询到Deployments的数量为:0
2021/04/20 12:56:58.889 [E] [getClusterInfoHandler.go:32]  获取Pod节点数量失败, err: Get "https://192.168.0.126:6443/api/v1/pods": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:56:58.889 [I] [getClusterInfoHandler.go:45]  查询到Pods的数量为:0
2021/04/20 12:56:58.889 [E] [getClusterInfoHandler.go:28]  获取Namespace节点数量失败, err: Get "https://192.168.0.126:6443/api/v1/namespaces": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:56:58.889 [I] [getClusterInfoHandler.go:45]  查询到Namespaces的数量为:0
2021/04/20 12:56:58.889 [E] [getClusterInfoHandler.go:34]  获取Secret节点数量失败, err: Get "https://192.168.0.126:6443/api/v1/secrets": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:56:58.889 [I] [getClusterInfoHandler.go:45]  查询到Secrets的数量为:0
2021/04/20 12:56:58.889 [E] [getClusterInfoHandler.go:30]  获取Service节点数量失败, err: Get "https://192.168.0.126:6443/api/v1/services": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:56:58.889 [I] [getClusterInfoHandler.go:45]  查询到Services的数量为:0
2021/04/20 12:56:58.889 [E] [getClusterInfoHandler.go:36]  获取Ingress节点数量失败, err: Get "https://192.168.0.126:6443/apis/extensions/v1beta1/ingresses": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:56:58.889 [I] [getClusterInfoHandler.go:45]  查询到Ingresses的数量为:0
2021/04/20 12:56:58.889 [I] [value.go:476]  获取数据:map[Daemonsets:%!s(int=0) Deployments:%!s(int=0) Ingresses:%!s(int=0) Namespaces:%!s(int=0) Nodes:%!s(int=0) Pods:%!s(int=0) Secrets:%!s(int=0) Services:%!s(int=0) Statefulsets:%!s(int=0)]
2021/04/20 12:57:02.676 [E] [getClusterInfoHandler.go:34]  获取Secret节点数量失败, err: Get "https://192.168.0.126:6443/api/v1/secrets": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:57:02.676 [I] [getClusterInfoHandler.go:45]  查询到Secrets的数量为:0
2021/04/20 12:57:02.677 [E] [getClusterInfoHandler.go:20]  获取Node节点数量失败, err: Get "https://192.168.0.126:6443/api/v1/nodes": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:57:02.677 [I] [getClusterInfoHandler.go:45]  查询到Nodes的数量为:0
2021/04/20 12:57:02.680 [E] [getClusterInfoHandler.go:24]  获取Deployment节点数量失败, err: Get "https://192.168.0.126:6443/apis/apps/v1/deployments": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:57:02.680 [I] [getClusterInfoHandler.go:45]  查询到Deployments的数量为:0
2021/04/20 12:57:02.680 [E] [getClusterInfoHandler.go:26]  获取StatefulSet节点数量失败, err: Get "https://192.168.0.126:6443/apis/apps/v1/statefulsets": dial tcp 192.168.0.126:6443: i/o timeout
2021/04/20 12:57:02.680 [I] [getClusterInfoHandler.go:45]  查询到Statefulsets的数量为:0
2021/04/20 12:57:02.681 [E] [getClusterInfoHandler.go:22]  获取DaemonSet节点数量失败, err: Get "https://192.168.0.126:6443/apis/apps/v1/daemonsets": dial tcp 192.168.0.126:6443: i/o timeout

**Comment by qinxiaohai** [comment]
请作者 看看是什么问题

**Comment by dotbalo** [comment]
"https://192.168.0.126:6443/apis/apps/v1/statefulsets": dial tcp 192.168.0.126:6443: i/o timeout

**Comment by qinxiaohai** [comment]
如何解决呢
